# This is a basic workflow to help you get started with Actions

name: Trufflehog CI Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secrets-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Trufflehog Actions Scan
      # You may pin to the exact commit or the version
        uses: armaanshah96/trufflehog-actions-scan@master
        with:
          # Use both regex and entropy checks
          scanArguments: "--regex --entropy=True -x secrets_scanning/exclude_patterns.txt --allow secrets_scanning/allow_ruleset.json"
